/*
  _____ _ _ _                    _             _       
 |  ___(_) | |_ ___ _ __   _ __ | |_   _  __ _(_)_ __  
 | |_  | | | __/ _ \ '__| | '_ \| | | | |/ _` | | '_ \ 
 |  _| | | | ||  __/ |    | |_) | | |_| | (_| | | | | |
 |_|   |_|_|\__\___|_|    | .__/|_|\__,_|\__, |_|_| |_|
                          |_|            |___/         
# A Template for Sync_handlerPlugin, a Filter Plugin
# Generated by the command: C:\Program Files\MADS\usr\local\bin\mads-plugin.exe -t filter -d C:\mirrorworld\instrumented_crutches_mads\sync_handler sync_handler
# Hostname: unknown
# Current working directory: C:\mirrorworld\instrumented_crutches_mads
# Creation date: 2026-05-12T10:44:00.483+0200
# NOTICE: MADS Version 2.0.0
*/
// Mandatory included headers
#include <filter.hpp>
#include <nlohmann/json.hpp>
#include <pugg/Kernel.h>
#include <cstdlib>
#include <ctime>
#include <chrono>
#include <iomanip>
#include <sstream>

// other includes as needed here

// Define the name of the plugin
#ifndef PLUGIN_NAME
#define PLUGIN_NAME "sync_handler"
#endif

// Load the namespaces
using namespace std;
using json = nlohmann::json;


// Plugin class. This shall be the only part that needs to be modified,
// implementing the actual functionality
class Sync_handlerPlugin : public Filter<json, json> {

public:

  // Typically, no need to change this
  string kind() override { return PLUGIN_NAME; }

  // Implement the actual functionality here
  // Return types:
  // return_type::success: processing is valid, go to process
  // return_type::retry: skip processing go to next loop
  // return_type::warning: content of _error is tracked with register_event
  // return_type::error: _error is traced, skip process
  // return_type::critical: execution stops
  return_type load_data(json const &input, string topic = "", vector<unsigned char> const *blob = nullptr) override {
    
    if (input.empty()) {
      return return_type::retry;
    }

    // Extract and parse the timestamp
    try {
      if (input.contains("timestamp") && input["timestamp"].is_object()) {
        if (input["timestamp"].contains("$date")) {
          string timestamp_str = input["timestamp"]["$date"].get<string>();
          _synchronized = check_sync_status(timestamp_str);
          //cout << "Timestamp: " << timestamp_str << ", Synchronized: " << (_synchronized ? "true" : "false") << endl;

          const auto now = std::chrono::steady_clock::now();

          if (_synchronized) {
            _synchronizing = false;
            _last_sync_attempt = now;
            //cout << "Device is synchronized. Next synchronization check will be performed after " << _health_status_period << " ms." << endl;
          } else {
            const bool cooldown_expired =
                !_synchronizing ||
                (now - _last_sync_attempt) >= std::chrono::seconds(8);

            if (cooldown_expired) {
              _synchronizing = true;
              _last_sync_attempt = now;
              const int restart_result = std::system("sudo systemctl restart chrony");
              _last_sync_command_ok = (restart_result == 0);
              //cout << "Attempted to restart chrony. Result: " << restart_result << endl;
            }
          }

          return return_type::success;
        }
      }

      // if input is not valid just ignore it and wait for the next one
      return return_type::success;

    } catch (const exception &e) {
      _error = string("Error parsing timestamp: ") + e.what();
      return return_type::warning;
    }

  }

  // We calculate the average of the last N values for each key and store it
  // into the output json object
  // Return types:
  // return_type::success: result is published
  // return_type::retry: don't publish, go to next loop
  // return_type::warning: content of _error is added to result befor publishing
  // return_type::error: _error is traced via register_event, don't publish
  // return_type::critical: execution stops
  return_type process(json &out, vector<unsigned char> *blob = nullptr) override {
    out.clear();

    // Send periodic agent_status if no command to send and 500ms have passed
    auto now = std::chrono::steady_clock::now();
    auto elapsed = std::chrono::duration_cast<std::chrono::milliseconds>(now - _last_health_status_time).count();
    
    // load the data as necessary and set the fields of the json out variable
    if (elapsed >= _health_status_period) {

      // Set the synchronized flag based on timestamp check
      out["info"]["synchronized"] = _synchronized;
      out["info"]["synchronizing"] = _synchronizing;
      out["agent_status"] = "idle";
      _last_health_status_time = now;
      
    } else {
      // if there is no command to send and not enough time has passed, don't send anything
      return return_type::retry;
    }
    
    // If there is a message to send, we must send the crutch side
    out["side"] = _side;

    // This sets the agent_id field in the output json object, only when it is
    // not empty
    if (!_agent_id.empty()) out["agent_id"] = _agent_id;
    return return_type::success;
  }
  
  void set_params(const json &params) override {
    // Call the parent class method to set the common parameters 
    // (e.g. agent_id, etc.)
    Filter::set_params(params);

    // provide sensible defaults for the parameters by setting e.g.
    _params["side"] = "unknown";

    // then merge the defaults with the actually provided parameters
    // params needs to be cast to json
    _params.merge_patch(params);

    _health_status_period = _params.value("health_status_period", 500); // default to 500 ms

    if (_params.contains("side") && (_params["side"] == "left" || _params["side"] == "right")) {
      _side = _params["side"].get<string>();
      _agent_id = "sync_handler_" + _side; // this is useful when the side field is not reachable
      std::cout << "Side set to " << _side << std::endl;
    } else {
      _error = "Side parameter not set or invalid (only 'left' or 'right' allowed).";
      std::cout << _error << std::endl;
      throw std::runtime_error(_error);
    }
      
  }

  // Implement this method if you want to provide additional information
  map<string, string> info() override { 
    // return a map of strings with additional information about the plugin
    // it is used to print the information about the plugin when it is loaded
    // by the agent
    
    return {};
    
  };

private:
  
  int _health_status_period = 500; // in milliseconds, default to 500 ms
  std::chrono::steady_clock::time_point _last_health_status_time = std::chrono::steady_clock::now();

  string _side = "unknown";
  // Define the fields that are used to store internal resources
  bool _synchronized = false;
  bool _synchronizing = false;
  bool _last_sync_command_ok = false;
  std::chrono::steady_clock::time_point _last_sync_attempt = std::chrono::steady_clock::time_point::min();
  
  // Helper function to parse ISO 8601 timestamp and get difference from now in seconds
  bool check_sync_status(const string &timestamp_str) {
    try {
      // Parse ISO 8601 format: "2026-05-11T19:23:49.454+0100"
      if (timestamp_str.size() < 24) {
        return false;
      }

      const size_t timezone_start = timestamp_str.find_last_of("+-");
      if (timezone_start == string::npos || timezone_start < 19) {
        return false;
      }

      const size_t fraction_start = timestamp_str.find('.', 19);
      const string seconds_part = timestamp_str.substr(0, 19);
      struct tm tm_time = {};
      istringstream time_stream(seconds_part);
      time_stream >> get_time(&tm_time, "%Y-%m-%dT%H:%M:%S");
      if (time_stream.fail()) {
        return false;
      }

      int milliseconds = 0;
      if (fraction_start != string::npos && fraction_start < timezone_start) {
        const string fraction_part = timestamp_str.substr(fraction_start + 1, timezone_start - fraction_start - 1);
        string milliseconds_str = fraction_part.substr(0, 3);
        while (milliseconds_str.size() < 3) {
          milliseconds_str.push_back('0');
        }
        milliseconds = stoi(milliseconds_str);
      }

      time_t parsed_seconds = 0;

      if (timestamp_str.back() == 'Z') {
#if defined(_WIN32)
        parsed_seconds = _mkgmtime(&tm_time);
#else
        parsed_seconds = timegm(&tm_time);
#endif
      } else {
        const string timezone_suffix = timestamp_str.substr(timezone_start);
        if (timezone_suffix.size() != 5 && timezone_suffix.size() != 6) {
          return false;
        }

        const int sign = (timezone_suffix[0] == '-') ? -1 : 1;
        const int offset_hours = stoi(timezone_suffix.substr(1, 2));
        const int offset_minutes = stoi(timezone_suffix.substr(3, 2));
        const int offset_seconds = sign * ((offset_hours * 60) + offset_minutes) * 60;

#if defined(_WIN32)
        parsed_seconds = _mkgmtime(&tm_time) - offset_seconds;
#else
        parsed_seconds = timegm(&tm_time) - offset_seconds;
#endif
      }

      auto now = chrono::system_clock::now();

      auto parsed_time_point = chrono::system_clock::from_time_t(parsed_seconds) + chrono::milliseconds(milliseconds);
      auto diff_ms = chrono::duration_cast<chrono::milliseconds>(now - parsed_time_point).count();
      auto abs_diff_ms = (diff_ms < 0) ? -diff_ms : diff_ms;

      auto current_time_ms = chrono::duration_cast<chrono::milliseconds>(now.time_since_epoch()).count();
      auto parsed_time_ms = chrono::duration_cast<chrono::milliseconds>(parsed_time_point.time_since_epoch()).count();

      //cout << "Current time: " << current_time_ms << ", Parsed time: " << parsed_time_ms << ", Difference: " << diff_ms << " ms" << endl;

      // Return true if difference is less than 5 seconds
      return abs_diff_ms < 5000;
      
    } catch (...) {
      return false;
    }
  }
  
};


/*
  ____  _             _             _      _
 |  _ \| |_   _  __ _(_)_ __     __| |_ __(_)_   _____ _ __
 | |_) | | | | |/ _` | | '_ \   / _` | '__| \ \ / / _ \ '__|
 |  __/| | |_| | (_| | | | | | | (_| | |  | |\ V /  __/ |
 |_|   |_|\__,_|\__, |_|_| |_|  \__,_|_|  |_| \_/ \___|_|
                |___/
Enable the class as plugin
*/
INSTALL_FILTER_DRIVER(Sync_handlerPlugin, json, json);


/*
                  _       
  _ __ ___   __ _(_)_ __  
 | '_ ` _ \ / _` | | '_ \ 
 | | | | | | (_| | | | | |
 |_| |_| |_|\__,_|_|_| |_|
                          
*/

int main(int argc, char const *argv[])
{
  Sync_handlerPlugin plugin;
  json params;
  json input, output;

  // Set example values to params
  params["test"] = "value";

  // Set the parameters
  plugin.set_params(params);

  // Set input data
  input["data"] = {
    {"AX", 1},
    {"AY", 2},
    {"AZ", 3}
  };

  // Set input data
  plugin.load_data(input);
  cout << "Input: " << input.dump(2) << endl;

  // Process data
  plugin.process(output);
  cout << "Output: " << output.dump(2) << endl;


  return 0;
}

