function [leftCrutch, rightCrutch] = import_h5_data(dataDir, idxs, groupName, debug)
% Return the data in table format, with one row per timestamp and one column per signal.
% The function reads the h5 files generated by the crutches and returns two tables, 
% one for the left crutch and one for the right crutch. 
% If one side is not present in the data, the corresponding table will be empty.
% Inputs:
%   dataDir: string, path to the folder containing the h5 files
%   idxs: array of integers, the acquisition ids to be imported (if more than one, the data will be concatenated)
%   groupName: string, the name of the group to be imported
%   debug: boolean, whether to print debug information

    if ~ismember(groupName, ["handle_loadcell", "tip_loadcell", "ppg", "ups"])
        error('Invalid group name. Must be one of: "handle_loadcell", "tip_loadcell", "ppg", "ups".');
    end

    leftCrutch = [];
    rightCrutch = [];
    for acquisitionId = idxs
        % seek for the crutches' h5 file
        crutchFiles = dir(fullfile(dataDir, sprintf('*_acq_%d.h5', acquisitionId)));
        if isempty(crutchFiles)
            error('HDF5 file not found for acquisition %d.', acquisitionId);
        end
        crutchFilename = fullfile(crutchFiles.folder, crutchFiles.name);
        infoH5 = h5info(crutchFilename);

        % feedback to user
        if debug
            fprintf('Selected file (id %d): %s\n', acquisitionId, string(crutchFilename));
            fprintf('H5 file info:\n');
            print_h5_fields(infoH5, '');
        end

        groupPath = "/" + groupName;
        datasets = h5info(crutchFilename, groupPath).Datasets;
        datasetNames = string({datasets.Name});

        timestampsRaw = read_dataset(crutchFilename, groupPath + "/timestamp");
        formattedTimestamps = parse_mads_timestamps(timestampsRaw);
        timestampUnixNs = double(round(posixtime(formattedTimestamps) .* 1e9));
        sides = read_dataset(crutchFilename, groupPath + "/side");
        
        exclude = ["timestamp", "side"];
        signalNames = datasetNames(~ismember(datasetNames, exclude));
        if isempty(signalNames)
            error('No signals found in group %s of file %s (except for timestamps and sides).', groupName, crutchFilename);
        end

        signalSeries = cell(numel(signalNames), 1);

        for s = 1:numel(signalNames)
            signalName = signalNames(s);
            signal = read_dataset(crutchFilename, groupPath + "/" + signalName);
            signalSeries{s} = double(signal(:));
        end

        signalNames = string(signalNames(:));
        tableVarNames = matlab.lang.makeUniqueStrings(matlab.lang.makeValidName(cellstr(signalNames)));

        baseTable = table(timestampUnixNs, 'VariableNames', {'timestamp'});
        for i = 1:numel(signalSeries)
            values = signalSeries{i};
            if isempty(values)
                warning('Signal %s in group %s of file %s is empty. Filling with NaN values.', signalNames(i), groupName, crutchFilename);
                baseTable.(tableVarNames{i}) = nan(height(baseTable), 1);
            else
                baseTable.(tableVarNames{i}) = values(1:height(baseTable));
            end
        end

        for sideLabel = ["left", "right"]
            rowMask = sides == sideLabel;
            if ~any(rowMask)
                continue
            end

            if sideLabel == "left"
                leftCrutch = [leftCrutch; baseTable(rowMask, :)];
            else
                rightCrutch = [rightCrutch; baseTable(rowMask, :)];
            end
        end
    end
end