function [left_crutch, right_crutch, coordinator, info] = import_hdf5_data(data_dir, idxs, group_name, debug)
% Return the data in table format, with one row per timestamp and one column per signal.
% The function reads the h5 files generated by the crutches and returns two tables, 
% one for the left crutch and one for the right crutch. 
% If one side is not present in the data, the corresponding table will be empty.
% Inputs:
%   data_dir: string, path to the folder containing the h5 files
%   idxs: array of integers, the acquisition ids to be imported (if more than one, the data will be concatenated)
%   group_name: string, the name of the group to be imported
%   debug: boolean, whether to print debug information

    if ~ismember(group_name, ["handle_loadcell", "tip_loadcell", "ppg", "ups", "coordinator", "pupil_neon"])
        error('Invalid group name. Must be one of: "handle_loadcell", "tip_loadcell", "ppg", "ups".');
    end

    left_crutch = [];
    right_crutch = [];
    coordinator = [];
    for i = 1:height(idxs)

        subject_id = idxs.subject_id(i);
        session_id = idxs.session_id(i);
        crutch_id = idxs.crutch_id(i);

        % seek for the crutches' h5 file
        crutch_files = dir(fullfile(data_dir, sprintf('sub_%d_session_%d_acq_%d.h5', [subject_id, session_id, crutch_id])));
        if isempty(crutch_files)
            error('HDF5 file not found for acquisition: sub %d, session %d, acq_%d.', [subject_id, session_id, crutch_id]);
        end
        crutch_filename = fullfile(crutch_files.folder, crutch_files.name);
        info_h5 = h5info(crutch_filename);

        % feedback to user
        if debug
            fprintf('Selected file (id %d): %s\n', crutch_id, string(crutch_filename));
            fprintf('H5 file info:\n');
            print_h5_fields(info_h5, '');
        end

        group_path = "/" + group_name;
        datasets = h5info(crutch_filename, group_path).Datasets;
        dataset_names = string({datasets.Name});

        timestamps_raw = read_dataset(crutch_filename, group_path + "/timestamp");
        formatted_timestamps = parse_mads_timestamps(timestamps_raw);
        timestamp_unix_ns = double(round(posixtime(formatted_timestamps) .* 1e9));

        exclude = ["timestamp"];
        if ismember(group_name,["handle_loadcell", "tip_loadcell", "ppg", "ups"])
            sides = read_dataset(crutch_filename, group_path + "/side");
            exclude = [exclude, "side"];
        end
        signal_names = dataset_names(~ismember(dataset_names, exclude));
        if isempty(signal_names)
            error('No signals found in group %s of file %s.', group_name, crutch_filename);
        end

        signal_series = cell(numel(signal_names), 1);

        for s = 1:numel(signal_names)
            signal_name = signal_names(s);
            signal = read_dataset(crutch_filename, group_path + "/" + signal_name);
            signal_series{s} = double(signal(:));
        end

        signal_names = string(signal_names(:));
        table_var_names = matlab.lang.makeUniqueStrings(matlab.lang.makeValidName(cellstr(signal_names)));

        base_table = table(timestamp_unix_ns, 'VariableNames', {'timestamp'});
        for c = 1:numel(signal_series)
            values = signal_series{c};
            if isempty(values)
                warning('Signal %s in group %s of file %s is empty. Filling with NaN values.', signal_names(i), group_name, crutch_filename);
                base_table.(table_var_names{c}) = nan(height(base_table), 1);
            else
                base_table.(table_var_names{c}) = values(1:height(base_table));
            end
        end

        if ismember(group_name,["handle_loadcell", "tip_loadcell", "ppg", "ups"])
            for side_label = ["left", "right"]
                row_mask = sides == side_label;
                if ~any(row_mask)
                    continue
                end

                this_crutch = base_table(row_mask, :);

                if side_label == "left"
                    left_crutch = [left_crutch; this_crutch];
                    info.("left_crutch").start_time(i,:) = this_crutch{1, "timestamp"};
                    info.("left_crutch").end_time(i,:) = this_crutch{end, "timestamp"};
                    info.("left_crutch").subject_id(i,:) = subject_id;
                    info.("left_crutch").session_id(i,:) = session_id;
                    info.("left_crutch").crutch_id(i,:) = crutch_id;
           
                else
                    right_crutch = [right_crutch; this_crutch];
                    info.("right_crutch").start_time(i,:) = this_crutch{1, "timestamp"};
                    info.("right_crutch").end_time(i,:) = this_crutch{end, "timestamp"};
                    info.("right_crutch").subject_id(i,:) = subject_id;
                    info.("right_crutch").session_id(i,:) = session_id;
                    info.("right_crutch").crutch_id(i,:) = crutch_id;
                end

            end
        else
            coordinator = base_table;
            info.("coordinator").start_time(i,:) = base_table{1, "timestamp"};
            info.("coordinator").end_time(i,:) = base_table{end, "timestamp"};
            info.("coordinator").subject_id(i,:) = subject_id;
            info.("coordinator").session_id(i,:) = session_id;
            info.("coordinator").crutch_id(i,:) = crutch_id;
        end
    end

    % convert to table
    for f = ["left_crutch", "right_crutch", "coordinator"]
        if isfield(info, f)
            info.(f) = struct2table(info.(f));
        end
    end
end