clear
close all
clc

% This script uses directly the h5 files generated by the crutches without exporting them to csv first
% 
%% Configuration
test_folder = fullfile("G:\Drive condivisi\ESCAPE - Fit4MedRob\Tests");
date = "20260707";
subject = "1";
session = "1";

% paths setup
campaign_dir = fullfile(test_folder, date);
raw_data_dir = fullfile(campaign_dir, '01_raw');
preprocessing_data_dir = fullfile(campaign_dir, '02_preprocessing');

%% Colors for plotting

% TIP: Use ColorBrewer site to choose the colors

% dark red: left crutch, dark green: right crutch
col.left = '#a50f15'; 
col.right = '#006d2c';

% condition colors
col.rest = '#264653';
col.stand_up = '#fdbf6f';
col.balance = '#1f78b4';
col.walk = '#a6cee3';
col.right_90 = '#b2df8a';
col.right_180 = '#33a02c';
col.left_90 = '#fb9a99';
col.left_180 = '#e31a1c';
col.sit_down = '#ff7f00';
col.ramp_up = '#cab2d6';
col.ramp_down = '#6a3d9a';
col.sync = '#264653';


%% Handle the acquisition index from the subject and session numbers using the info file
% Every subject and session combination can have multiple acquisition IDs, which are stored in the info.xlsx file. 
% This section reads the info file and extracts the corresponding acquisition IDs for the specified subject and session.
%
% Since multiple trials may share the same subject ID and session ID but
% have different test IDs for various reasons, the user is required to
% specify in the "info.xlsx" file the test IDs associated with the Pupil
% recordings and the test IDs associated with the HDF5 files.
% 

info = readcell(fullfile(raw_data_dir, 'info.xlsx')); % read as cell array to handle mixed data types
info = cell2table(info(2:end, :), 'VariableNames', info(1, :)); % convert to table for easier manipulation
variable_names = string(info.Properties.VariableNames);

subject_id_column = find(strcmpi(variable_names, 'subject'), 1);
session_id_column = find(strcmpi(variable_names, 'session'), 1);
pupil_id_column = find(strcmpi(variable_names, 'pupil_id'), 1);
crutch_id_column = find(strcmpi(variable_names, 'crutch_id'), 1);
if isempty(subject_id_column) || isempty(session_id_column) || isempty(pupil_id_column) || isempty(crutch_id_column)
    error('The info.xlsx file must contain columns named "subject", "session", "pupil_id", and "crutch_id".');
end

row_mask = string(info{:, subject_id_column}) == subject & string(info{:, session_id_column}) == session;
if ~any(row_mask)
    error('No rows found for subject %s and session %s.', subject, session);
end

idxs.subject_id = info{row_mask, subject_id_column};
idxs.session_id = info{row_mask, session_id_column};
idxs.pupil_id = info{row_mask, pupil_id_column};
idxs.crutch_id = info{row_mask, crutch_id_column};
idxs = struct2table(idxs);


%% Analysis pipeline for each subject and session combination (one or more acquisition IDs)
% Get the events data (from the "coordinator" field) to separate the data into different phases (e.g., walking, etc.) and extract the metric values for each phase.
% Get the tip loadcell data, extract the metric values for each phase
% Repeat for the handle loadcell, ppg, and ups data for each phase

% import crutches data from the hdf5 file
[tip_left, tip_right, ~, tip_info] = import_hdf5_data(fullfile(raw_data_dir, "crutch"), idxs, "tip_loadcell", false);
% [handle_left, handle_right,~] = import_hdf5_data(fullfile(raw_data_dir, "crutch"), idxs, "handle_loadcell", false);
% [ppg_left, ppg_right,~] = import_hdf5_data(fullfile(raw_data_dir, "crutch"), idxs, "ppg", false);
% [ups_left, ups_right,~] = import_hdf5_data(fullfile(raw_data_dir, "crutch"), idxs, "ups", false);

% import the eye tracker data from the pupil neon recording folder amd
% correct the time delay between devices
[gaze, fixations, saccades, blinks, imu, events, ecg] = import_pupil_neon_and_ecg_data(campaign_dir, idxs, tip_info);


%% Raw data visualization (optional)
% Tip loadcell data visualization
if false
    figure(101)
    t0 = min([tip_left.timestamp; tip_right.timestamp]);
    plot((tip_left.timestamp-t0)*1e-9, tip_left.force,'.', 'Color', col.left)
    hold on
    plot((tip_right.timestamp-t0)*1e-9, tip_right.force,'.', 'Color', col.right)
    plot_events(events, t0, col, -10, 700, 500)
    xlabel('Time [s]')
    ylabel('Force [N]')
    title("TIP")
    ylim([0 700])
    grid on
end

% Handle loadcell data visualization
if false
    figure(102)
    t0 = min([handle_left.timestamp; handle_right.timestamp]);

    ax1 = subplot(8,1,1);
    plot((handle_left.timestamp-t0)*1e-9, handle_left.force_up_back,'.', 'Color', col.left)
    hold on
    plot((handle_right.timestamp-t0)*1e-9, handle_right.force_up_back,'.', 'Color', col.right)
    plot_events(events, t0, col, -10, 500, 300)
    xlabel('Time [s]')
    ylabel('Force [N]')
    ylim([-10 550])
    grid on
    title("UP BACK")

    ax2 = subplot(8,1,2);
    plot((handle_left.timestamp-t0)*1e-9, handle_left.force_up_front,'.', 'Color', col.left)
    hold on
    plot((handle_right.timestamp-t0)*1e-9, handle_right.force_up_front,'.', 'Color', col.right)
    plot_events(events, t0, col, -10, 500, nan)
    xlabel('Time [s]')
    ylabel('Force [N]')
    ylim([-10 550])
    grid on
    title("UP FRONT")

    ax3 = subplot(8,1,3);
    plot((handle_left.timestamp-t0)*1e-9, handle_left.force_down_back,'.', 'Color', col.left)
    hold on
    plot((handle_right.timestamp-t0)*1e-9, handle_right.force_down_back,'.', 'Color', col.right)
    plot_events(events, t0, col, -10, 50, nan)
    xlabel('Time [s]')
    ylabel('Force [N]')
    ylim([-10 55])
    grid on
    title("DOWN BACK")

    ax4 = subplot(8,1,4);
    plot((handle_left.timestamp-t0)*1e-9, handle_left.force_down_front,'.', 'Color', col.left)
    hold on
    plot((handle_right.timestamp-t0)*1e-9, handle_right.force_down_front,'.', 'Color', col.right)
    plot_events(events, t0, col, -10, 50, nan)
    xlabel('Time [s]')
    ylabel('Force [N]')
    ylim([-10 55])
    grid on
    title("DOWN FRONT")

    ax5 = subplot(8,1,5);
    plot((handle_left.timestamp-t0)*1e-9, handle_left.force_ext_back,'.', 'Color', col.left)
    hold on
    plot((handle_right.timestamp-t0)*1e-9, handle_right.force_ext_back,'.', 'Color', col.right)
    plot_events(events, t0, col, -10, 50, nan)
    xlabel('Time [s]')
    ylabel('Force [N]')
    ylim([-10 55])
    grid on
    title("EXT BACK")

    ax6 = subplot(8,1,6);
    plot((handle_left.timestamp-t0)*1e-9, handle_left.force_ext_front,'.', 'Color', col.left)
    hold on
    plot((handle_right.timestamp-t0)*1e-9, handle_right.force_ext_front,'.', 'Color', col.right)
    plot_events(events, t0, col, -10, 50, nan)
    xlabel('Time [s]')
    ylabel('Force [N]')
    ylim([-10 55])
    grid on
    title("EXT FRONT")

    ax7 = subplot(8,1,7);
    plot((handle_left.timestamp-t0)*1e-9, handle_left.force_int_back,'.', 'Color', col.left)
    hold on
    plot((handle_right.timestamp-t0)*1e-9, handle_right.force_int_back,'.', 'Color', col.right)
    plot_events(events, t0, col, -10, 50, nan)
    xlabel('Time [s]')
    ylabel('Force [N]')
    ylim([-10 55])
    grid on
    title("INT BACK")

    ax8 = subplot(8,1,8);
    plot((handle_left.timestamp-t0)*1e-9, handle_left.force_int_front,'.', 'Color', col.left)
    hold on
    plot((handle_right.timestamp-t0)*1e-9, handle_right.force_int_front,'.', 'Color', col.right)
    plot_events(events, t0, col, -10, 50, nan)
    xlabel('Time [s]')
    ylabel('Force [N]')
    ylim([-10 55])
    grid on
    title("INT FRONT")

    linkaxes([ax1 ax2 ax3 ax4 ax5 ax6 ax7 ax8], 'x')

end

% PPG data visualization
if false
    figure(103)
    t0 = min([ppg_left.timestamp; ppg_right.timestamp]);
    ax1 = subplot(2,1,1);
    plot(double(ppg_left.timestamp-t0)*1e-9, ppg_left.ir,'.', 'Color', col.left)
    hold on
    plot(double(ppg_right.timestamp-t0)*1e-9, ppg_right.ir,'.', 'Color', col.right)
    plot_events(events, t0, col, min([ppg_right.ir; ppg_left.ir]), max([ppg_right.ir; ppg_left.ir]), 0)
    xlabel('Time [s]')
    ylabel('Signal')
    grid on
    title("IR")

    ax2 = subplot(2,1,2);
    plot(double(ppg_left.timestamp-t0)*1e-9, ppg_left.red,'.', 'Color', col.left)
    hold on
    plot(double(ppg_right.timestamp-t0)*1e-9, ppg_right.red,'.', 'Color', col.right)
    plot_events(events, t0, col, min([ppg_right.red; ppg_left.red]), max([ppg_right.red; ppg_left.red]), 0)
    xlabel('Time [s]')
    ylabel('Signal')
    grid on
    title("RED")

    linkaxes([ax1 ax2],'x')
end

% UPS data visualization
if false
    figure(104)
    t0 = min([ups_left.timestamp; ups_right.timestamp]);
    plot(double(ups_left.timestamp-t0)*1e-9, ups_left.info_voltage,'.', 'Color', col.left)
    hold on
    plot(double(ups_right.timestamp-t0)*1e-9, ups_right.info_voltage,'.', 'Color', col.right)
    plot_events(events, t0, col, 0, 5, 3)
    xlabel('Time [s]')
    ylabel('Voltage [V]')
    ylim([0 5])
    grid on
end

% ECG
if true
    figure(105)
    t0 = ecg.timestamp(1);

    ax1 = subplot(3,1,1);
    plot(double(ecg.timestamp-t0)*1e-9, ecg.ecg, 'Color', col.left)
    hold on
    plot_events(events, t0, col, -2, 2, 1.5)
    xlabel('Time [s]')
    ylabel('ECG')
    ylim([-2 2])
    grid on

    ax2 = subplot(3,1,2);
    plot(double(ecg.timestamp-t0)*1e-9, ecg.hr, '.', 'Color', col.left)
    hold on
    plot_events(events, t0, col, 30, 200, 180)
    xlabel('Time [s]')
    ylabel('ECG')
    ylim([30 200])
    grid on

    ax3 = subplot(3,1,3);
    plot(double(ecg.timestamp-t0)*1e-9, ecg.rr, '.', 'Color', col.left)
    hold on
    plot_events(events, t0, col, 0, 1000, 900)
    xlabel('Time [s]')
    ylabel('ECG')
    ylim([0 1000])
    grid on

    linkaxes([ax1 ax2 ax3], 'x')
end

%% Data analysis and metrics extraction

% Tip loadcell data analysis
% HX711 loadcell amplifier introduce some unwanted spikes in the force signal. We remove them with a custom filter
tip_left.force = filterLoadcell(tip_left.force);
tip_right.force = filterLoadcell(tip_right.force);


% DA SISTEMARE:
% Bisogna dividere per eventi
% Analizzare i picchi
% Rms
% Simmetrie varie
t = (tip_left.timestamp-tip_left.timestamp(1))*10^-9;
[left_peaks, left_locs, left_widths, left_proms] = findpeaks(tip_left.force,t,'MinPeakProminence',prctile(tip_left.force,60),'Annotate','extents');

t = (tip_right.timestamp-tip_left.timestamp(1))*10^-9;
[right_peaks, right_locs, right_widths, right_proms] = findpeaks(tip_right.force,t,'MinPeakProminence',prctile(tip_right.force,60),'Annotate','extents');

% rimuovo i picchi trovati sugli spikes controllando
% l'ampiezza del picco. Se minore di 0.1 s non ha senso di
% esistere
threshold_width = 0.1; % seconds
left_peaks(left_widths<threshold_width) = [];
left_locs(left_widths<threshold_width) = [];
left_proms(left_widths<threshold_width) = [];
left_widths(left_widths<threshold_width) = [];

right_peaks(right_widths<threshold_width) = [];
right_locs(right_widths<threshold_width) = [];
right_proms(right_widths<threshold_width) = [];
right_widths(right_widths<threshold_width) = [];

results.("left").peaks.mean = mean(left_peaks);
results.("left").peaks.rms = rms(left_peaks);
results.("left").peaks.std = std(left_peaks);

results.("left").prominences.mean = mean(left_proms);
results.("left").prominences.rms = rms(left_proms);
results.("left").prominences.std = std(left_proms);

results.("left").widths.mean = mean(left_widths);
results.("left").widths.rms = rms(left_widths);
results.("left").widths.std = std(left_widths);

results.("right").peaks.mean = mean(right_peaks);
results.("right").peaks.rms = rms(right_peaks);
results.("right").peaks.std = std(right_peaks);

results.("right").prominences.mean = mean(right_proms);
results.("right").prominences.rms = rms(right_proms);
results.("right").prominences.std = std(right_proms);

results.("right").widths.mean = mean(right_widths);
results.("right").widths.rms = rms(right_widths);
results.("right").widths.std = std(right_widths);


%% Check sync
% figure(101)
% plot(tip_left.force,'.', 'Color', col.left)
% ylabel('Force [N]')
% ylim([0 700])
% grid on
% 
% tip_left.timestamp(6267)

