clear
close all
clc

% This script uses directly the h5 files generated by the crutches without exporting them to csv first
% 
%% Configuration
test_folder = fullfile("G:\Drive condivisi\ESCAPE - Fit4MedRob\Tests");
date = "20260707";
subject = "1";
session = "5";
crutch_id = "33"; % set as "" to load all the hdf5 files related to the selected subject and session

% paths setup
campaign_dir = fullfile(test_folder, date);
raw_data_dir = fullfile(campaign_dir, '01_raw'); 
preprocessing_data_dir = fullfile(campaign_dir, '02_preprocessing');

%% Colors for plotting

% TIP: Use ColorBrewer site to choose the colors

% dark red: left crutch, dark green: right crutch
col.left = '#a50f15'; 
col.right = '#006d2c';

% condition colors
col.rest = '#264653';
col.stand_up = '#fdbf6f';
col.balance = '#1f78b4';
col.walk = '#a6cee3';
col.right_90 = '#b2df8a';
col.right_180 = '#33a02c';
col.left_90 = '#fb9a99';
col.left_180 = '#e31a1c';
col.sit_down = '#ff7f00';
col.ramp_up = '#cab2d6';
col.ramp_down = '#6a3d9a';
col.sync = '#264653';


%% Handle the acquisition index from the subject and session numbers using the info file
% Every subject and session combination can have multiple acquisition IDs, which are stored in the info.xlsx file. 
% This section reads the info file and extracts the corresponding acquisition IDs for the specified subject and session.
%
% Since multiple trials may share the same subject ID and session ID but
% have different test IDs for various reasons, the user is required to
% specify in the "info.xlsx" file the test IDs associated with the Pupil
% recordings and the test IDs associated with the HDF5 files.
% 

info = readcell(fullfile(raw_data_dir, 'info.xlsx')); % read as cell array to handle mixed data types
info = cell2table(info(2:end, :), 'VariableNames', info(1, :)); % convert to table for easier manipulation
variable_names = string(info.Properties.VariableNames);

subject_id_column = find(strcmpi(variable_names, 'subject'), 1);
session_id_column = find(strcmpi(variable_names, 'session'), 1);
pupil_id_column = find(strcmpi(variable_names, 'pupil_id'), 1);
crutch_id_column = find(strcmpi(variable_names, 'crutch_id'), 1);
if isempty(subject_id_column) || isempty(session_id_column) || isempty(pupil_id_column) || isempty(crutch_id_column)
    error('The info.xlsx file must contain columns named "subject", "session", "pupil_id", and "crutch_id".');
end

row_mask = string(info{:, subject_id_column}) == subject & string(info{:, session_id_column}) == session;
if ~any(row_mask)
    error('No rows found for subject %s and session %s.', subject, session);
end

idxs.subject_id = info{row_mask, subject_id_column};
idxs.session_id = info{row_mask, session_id_column};
idxs.pupil_id = info{row_mask, pupil_id_column};
idxs.crutch_id = info{row_mask, crutch_id_column};
idxs = struct2table(idxs);


%% Analysis pipeline for each subject and session combination (one or more acquisition IDs)
% Get the events data (from the "coordinator" field) to separate the data into different phases (e.g., walking, etc.) and extract the metric values for each phase.
% Get the tip loadcell data, extract the metric values for each phase
% Repeat for the handle loadcell, ppg, and ups data for each phase

% if crutch id is specified remove every rows with diffent crutch_id
if crutch_id ~= ""
    row_mask = string(idxs.crutch_id) == crutch_id;
    idxs(~row_mask,:) = [];
end

% import crutches data from the hdf5 file
[tip_left, tip_right, ~, tip_info] = import_hdf5_data(fullfile(raw_data_dir, "crutch"), idxs, "tip_loadcell", false);


% Tip loadcell data visualization
figure(101)
plot(tip_left.force,'.', 'Color', col.left)
xlabel('# sample')
ylabel('Force [N]')
title("TIP")
ylim([0 700])
grid on


%% Check sync

sample_number = 162973;
sprintf("time to save: %18d", tip_left.timestamp(sample_number))

