/*
  _____ _ _ _                    _             _       
 |  ___(_) | |_ ___ _ __   _ __ | |_   _  __ _(_)_ __  
 | |_  | | | __/ _ \ '__| | '_ \| | | | |/ _` | | '_ \ 
 |  _| | | | ||  __/ |    | |_) | | |_| | (_| | | | | |
 |_|   |_|_|\__\___|_|    | .__/|_|\__,_|\__, |_|_| |_|
                          |_|            |___/         
# A Template for Handle_loadcellPlugin, a Filter Plugin
# Generated by the command: C:\Program Files\MADS\usr\local\bin\mads-plugin.exe -t filter -d C:\mirrorworld\instrumented_crutches_mads\handle_loadcell handle_loadcell
# Hostname: unknown
# Current working directory: C:\mirrorworld\instrumented_crutches_mads
# Creation date: 2026-03-12T13:57:29.688+0100
# NOTICE: MADS Version 2.0.0
*/
// Mandatory included headers
#include <filter.hpp>
#include <nlohmann/json.hpp>
#include <pugg/Kernel.h>
#include <array>
#include <cstdint>

#if defined(RPI)
extern "C" {
#include "ADS1263.h"
}
#endif

// other includes as needed here

// Define the name of the plugin
#ifndef PLUGIN_NAME
#define PLUGIN_NAME "handle_loadcell"
#endif

// Load the namespaces
using namespace std;
using json = nlohmann::json;


// Plugin class. This shall be the only part that needs to be modified,
// implementing the actual functionality
class Handle_loadcellPlugin : public Filter<json, json> {

public:

  ~Handle_loadcellPlugin() override {
#ifdef RPI
    if (_adc_initialized) {
      DEV_Module_Exit();
    }
#endif
  }

  // Typically, no need to change this
  string kind() override { return PLUGIN_NAME; }

  // Implement the actual functionality here
  // Return types:
  // return_type::success: processing is valid, go to process
  // return_type::retry: skip processing go to next loop
  // return_type::warning: content of _error is tracked with register_event
  // return_type::error: _error is traced, skip process
  // return_type::critical: execution stops
  return_type load_data(json const &input, string topic = "", vector<unsigned char> const *blob = nullptr) override {
    // Do something with the input data
    return return_type::success;
  }

  // We calculate the average of the last N values for each key and store it
  // into the output json object
  // Return types:
  // return_type::success: result is published
  // return_type::retry: don't publish, go to next loop
  // return_type::warning: content of _error is added to result befor publishing
  // return_type::error: _error is traced via register_event, don't publish
  // return_type::critical: execution stops
  return_type process(json &out, vector<unsigned char> *blob = nullptr) override {
    out.clear();

#ifdef RPI
    if (!_adc_initialized) {
      _error = "ADS1263 non inizializzato: chiamare set_params() prima di process().";
      return return_type::error;
    }

    ADS1263_GetAll(_channel_list.data(), _raw_values.data(), static_cast<int>(_channel_list.size()));

    json channels = json::object();
    for (size_t i = 0; i < _channel_list.size(); ++i) {
      const auto raw = _raw_values[i];
      const bool negative = (raw >> 31U) == 1U;
      const double voltage = negative
        ? -(2.0 * _ref_voltage - static_cast<double>(raw) / 2147483648.0 * _ref_voltage)
        : (static_cast<double>(raw) / 2147483647.0 * _ref_voltage);

      const string key = "IN" + to_string(_channel_list[i]);
      channels[key] = {
        {"raw", raw},
        {"voltage", voltage}
      };
    }

    out["channels"] = channels;
#else
    _error = "Lettura ADS1263 disponibile solo su Linux (driver C sysfs/SPI).";
    return return_type::error;
#endif

    // load the data as necessary and set the fields of the json out variable

    // This sets the agent_id field in the output json object, only when it is
    // not empty
    if (!_agent_id.empty()) out["agent_id"] = _agent_id;
    return return_type::success;
  }
  
  void set_params(const json &params) override {
    // Call the parent class method to set the common parameters 
    // (e.g. agent_id, etc.)
    Filter::set_params(params);

    _params["adc1_rate"] = 7;   // ADS1263_100SPS
    _params["ref_voltage"] = 4.12;

    // then merge the defaults with the actually provided parameters
    // params needs to be cast to json
    _params.merge_patch(params);

#ifdef RPI
    _ref_voltage = _params.value("ref_voltage", 4.12);
    const int adc_rate = _params.value("adc1_rate", 7);

    if (_adc_initialized) {
      DEV_Module_Exit();
      _adc_initialized = false;
    }

    if (DEV_Module_Init() != 0) {
      _error = "DEV_Module_Init fallita.";
      return;
    }

    ADS1263_SetMode(0);
    if (ADS1263_init_ADC1(static_cast<ADS1263_DRATE>(adc_rate)) != 0) {
      DEV_Module_Exit();
      _error = "ADS1263_init_ADC1 fallita.";
      return;
    }

    _adc_initialized = true;
#endif
      
  }

  // Implement this method if you want to provide additional information
  map<string, string> info() override { 
    // return a map of strings with additional information about the plugin
    // it is used to print the information about the plugin when it is loaded
    // by the agent
    
    return {};
    
  };

private:
  // Define the fields that are used to store internal resources
  array<uint8_t, 8> _channel_list{0, 1, 2, 3, 4, 5, 6, 7};
  array<uint32_t, 8> _raw_values{};
  double _ref_voltage = 4.12;
  bool _adc_initialized = false;
};


/*
  ____  _             _             _      _
 |  _ \| |_   _  __ _(_)_ __     __| |_ __(_)_   _____ _ __
 | |_) | | | | |/ _` | | '_ \   / _` | '__| \ \ / / _ \ '__|
 |  __/| | |_| | (_| | | | | | | (_| | |  | |\ V /  __/ |
 |_|   |_|\__,_|\__, |_|_| |_|  \__,_|_|  |_| \_/ \___|_|
                |___/
Enable the class as plugin
*/
INSTALL_FILTER_DRIVER(Handle_loadcellPlugin, json, json);


/*
                  _       
  _ __ ___   __ _(_)_ __  
 | '_ ` _ \ / _` | | '_ \ 
 | | | | | | (_| | | | | |
 |_| |_| |_|\__,_|_|_| |_|
                          
*/

int main(int argc, char const *argv[])
{
  Handle_loadcellPlugin plugin;
  json params;
  json input, output;

  // Set example values to params
  params["test"] = "value";

  // Set the parameters
  plugin.set_params(params);

  // Set input data
  input["data"] = {
    {"AX", 1},
    {"AY", 2},
    {"AZ", 3}
  };

  // Set input data
  plugin.load_data(input);
  cout << "Input: " << input.dump(2) << endl;

  // Process data
  plugin.process(output);
  cout << "Output: " << output.dump(2) << endl;


  return 0;
}

