---
id: 1835cac1-e1f2-49e6-a27f-7ce10ef61abf
---
treeView-beta
            "Tests"
                "YYYYMMDD"
                    "00_protocols"
                    "01_raw"
                        "crutch"
                            "sub_<S>_session_<C>_acq_<A>_data.h5"
                            "sub_<S>_session_<C>_acq_<A>_info.csv"
                            "..."
                        "ecg"
                            "DD MMM YYYY, HH_mm_ss-N.csv"
                            "..."
                        "media"
                            "..."
                        "pupil"
                            "sub_<S>_session_<C>_acq_<A>-<pupilID>"
                            "..."
                    "02_preprocessing"
                        "pupil"
                            "sub_<S>_session_<C>_acq_<A>-<pupilID>"
                            "..."
                    "03_analysis"
                    "04_results"
                "..."
