/*
  _____ _ _ _                    _             _       
 |  ___(_) | |_ ___ _ __   _ __ | |_   _  __ _(_)_ __  
 | |_  | | | __/ _ \ '__| | '_ \| | | | |/ _` | | '_ \ 
 |  _| | | | ||  __/ |    | |_) | | |_| | (_| | | | | |
 |_|   |_|_|\__\___|_|    | .__/|_|\__,_|\__, |_|_| |_|
                          |_|            |___/         
# A Template for ControllerPlugin, a Filter Plugin
# Generated by the command: C:\Program Files\MADS\usr\local\bin\mads-plugin.exe -t filter -d C:\mirrorworld\instrumented_crutches\controller controller
# Hostname: unknown
# Current working directory: C:\mirrorworld\instrumented_crutches
# Creation date: 2026-01-11T21:54:49.684+0100
# NOTICE: MADS Version 1.4.0
*/
// Mandatory included headers
#include <filter.hpp>
#include <nlohmann/json.hpp>
#include <pugg/Kernel.h>

// other includes as needed here

// Define the name of the plugin
#ifndef PLUGIN_NAME
#define PLUGIN_NAME "controller"
#endif

// Load the namespaces
using namespace std;
using json = nlohmann::json;


// Plugin class. This shall be the only part that needs to be modified,
// implementing the actual functionality
class ControllerPlugin : public Filter<json, json> {

public:

  // Typically, no need to change this
  string kind() override { return PLUGIN_NAME; }

  // Implement the actual functionality here
  return_type load_data(json const &input, string topic = "") override {

    if (topic == "agent_event") {
      _last_agent_event = input;
      std::cout << "Controller: agent_event received -> " << input.dump() << std::endl;
      return return_type::success;
    }
    
    // if topic is "command", process commands here
    if (topic == "ws_command") {
      if (!input.contains("command")) {
        _error = "Controller: missing command in ws_command payload";
        return return_type::warning;
      }

      string action = input["command"];

      if (action == "start") {
        if (_acquiring) {
          _error = "Controller: start requested while already acquiring";
          return return_type::warning;
        }
        if (!input.contains("id")) {
          _error = "Controller: start command requires an id";
          return return_type::error;
        }

        _send_command = true;
        _command_to_send = action;
        _id_to_send = input.value("id", -1);
        std::cout << "Controller: Sending command " << action << std::endl;
        return return_type::success;
      }

      if (action == "stop") {
        if (_acquiring == false) {
          _error = "Controller: stop requested while not acquiring";
          return return_type::warning;
        }
        _send_command = true;
        _command_to_send = action;
        std::cout << "Controller: Sending command " << action << std::endl;
        return return_type::success;
      }

      if (action == "set_offset") {
        _send_command = true;
        _command_to_send = action;
        std::cout << "Controller: Sending command " << action << std::endl;
        return return_type::success;
      }

      _error = "Controller: unknown command '" + action + "'";
      return return_type::warning;
    }

    return return_type::success;
  }

  // We calculate the average of the last N values for each key and store it
  // into the output json object
  return_type process(json &out) override {
    out.clear();

    // load the data as necessary and set the fields of the json out variable
    if (_send_command) {
      out["command"] = _command_to_send;

      if (_command_to_send == "start") {
        out["id"] = _id_to_send; // include id only for start command
        _acquiring = true;
      } else if (_command_to_send == "stop") {
        _acquiring = false;
      }
      else if (_command_to_send == "set_offset") {
        //_error = "set_offset command not implemented in ControllerPlugin";
      }
      // do nothing special for set_offset

      _send_command = false; // reset the flag
    }
    else {
      return return_type::retry;
    }

    // This sets the agent_id field in the output json object, only when it is
    // not empty
    if (!_agent_id.empty()) out["agent_id"] = _agent_id;
    return return_type::success;
  }
  
  void set_params(void const *params) override {
    // Call the parent class method to set the common parameters 
    // (e.g. agent_id, etc.)
    Filter::set_params(params);

    // provide sensible defaults for the parameters by setting e.g.
    _params["some_field"] = "default_value";
    // more here...

    // then merge the defaults with the actually provided parameters
    // params needs to be cast to json
    _params.merge_patch(*(json *)params);
      
  }

  // Implement this method if you want to provide additional information
  map<string, string> info() override { 
    // return a map of strings with additional information about the plugin
    // it is used to print the information about the plugin when it is loaded
    // by the agent
    
    return {};
    
  };

private:
  // Define the fields that are used to store internal resources
  bool _acquiring = false;
  bool _send_command = false;
  string _command_to_send = "";
  int _id_to_send = -1;
  json _last_agent_event;
};


/*
  ____  _             _             _      _
 |  _ \| |_   _  __ _(_)_ __     __| |_ __(_)_   _____ _ __
 | |_) | | | | |/ _` | | '_ \   / _` | '__| \ \ / / _ \ '__|
 |  __/| | |_| | (_| | | | | | | (_| | |  | |\ V /  __/ |
 |_|   |_|\__,_|\__, |_|_| |_|  \__,_|_|  |_| \_/ \___|_|
                |___/
Enable the class as plugin
*/
INSTALL_FILTER_DRIVER(ControllerPlugin, json, json);


/*
                  _       
  _ __ ___   __ _(_)_ __  
 | '_ ` _ \ / _` | | '_ \ 
 | | | | | | (_| | | | | |
 |_| |_| |_|\__,_|_|_| |_|
                          
*/

int main(int argc, char const *argv[])
{
  ControllerPlugin plugin;
  json params;
  json input, output;

  // Set example values to params
  params["test"] = "value";

  // Set the parameters
  plugin.set_params(&params);

  // Set input data
  input["data"] = {
    {"AX", 1},
    {"AY", 2},
    {"AZ", 3}
  };

  // Set input data
  plugin.load_data(input);
  cout << "Input: " << input.dump(2) << endl;

  // Process data
  plugin.process(output);
  cout << "Output: " << output.dump(2) << endl;


  return 0;
}

