#   ____                                      
#  / ___|___  _ __ ___  _ __ ___   ___  _ __  
# | |   / _ \| '_ ` _ \| '_ ` _ \ / _ \| '_ \ 
# | |__| (_) | | | | | | | | | | | (_) | | | |
#  \____\___/|_| |_| |_|_| |_| |_|\___/|_| |_|
# 


[agents]
# Settings shared by all agents
frontend_address = "tcp://localhost:9090"
backend_address = "tcp://localhost:9091"
settings_address = "tcp://localhost:9092"
compress = true
timecode_fps = 25


#  __  __                   _ _ _   _     _      
# |  \/  | ___  _ __   ___ | (_) |_| |__ (_) ___ 
# | |\/| |/ _ \| '_ \ / _ \| | | __| '_ \| |/ __|
# | |  | | (_) | | | | (_) | | | |_| | | | | (__ 
# |_|  |_|\___/|_| |_|\___/|_|_|\__|_| |_|_|\___|
#                                                

[broker]
frontend_address = "tcp://*:9090"
backend_address = "tcp://*:9091"
settings_address = "tcp://*:9092"


[logger]
mongo_uri = "mongodb://localhost:27017"
mongo_db = "mads_test"
# sub_topic = ["logger", "metadata", "rfid", "skeleton", "platform", "image", "agent_event", "bridge", "perf_assess"]
# or, subscribe to all topics:
sub_topic = [""]
max_length = 75
initially_paused = false


[bridge]
# default publish topic (if not passed via CLI)
sub_topic = ["publish"]
pub_topic = "bridge"


[feedback]
# Subscribes to ALL topics
sub_topic = [""]
print_width = 0
indent_width = 2

[metadata]
# Topic to publish to (single string!)
pub_topic = "metadata"


[perf_assess]
pub_topic = "perf_assess"

[publish]
pub_topic = "publish"

[dealer]
sub_topic = ["publish", "spawner"]
pub_topic = "dealer"
dealer_address = "tcp://*:9093"

[worker]
pub_topic = "worker"
dealer_address = "tcp://localhost:9093"


#  ____  _             _           
# |  _ \| |_   _  __ _(_)_ __  ___ 
# | |_) | | | | |/ _` | | '_ \/ __|
# |  __/| | |_| | (_| | | | | \__ \
# |_|   |_|\__,_|\__, |_|_| |_|___/
#                |___/             
#

[echoj]
# Topic to publish to (single string!)
pub_topic = "echoj"
sub_topic = ["rfid"]


[clock]
# Topic to publish to (single string!)
pub_topic = "clock"
period = 200


[monitor]
sub_topic = [""]
col_widths = [18, 15, 15]
yellow = 0.1
red = 0.1
silent = true

# --------------------------------
# --------------------------------
# Instrumented Crutches Agents
# --------------------------------
# --------------------------------

# --------------------------------
# Controllers
# --------------------------------

[web_server]
sub_topic = ["status"]
pub_topic = "ws_command"

# execution command example:
# mads-filter coordinator -b
[coordinator]
sub_topic = ["ws_command"]
pub_topic = "coordinator"
period = 10
health_status_period = 500 # ms


# execution command example:
# mads-filter status_handler
[status_handler] 
sub_topic = ["agent_event", "coordinator", "ups", "hdf5_writer", "tip_loadcell", "handle_loadcell", "ppg", "pupil_neon"] # add other relevant topics to monitor (startup events, error events and shutdown events from all agents are automatically published to "agent_event" topic)
pub_topic = "status"
unreachable_agent_timeout = 3000 # ms
debug = false

# execution command example:
# source venv/bin/activate
# python ups.py
[ups]
pub_topic = "ups"
health_status_period = 1000 # ms
i2c_bus = 1
i2c_address = 67 # decimal for 0x43
battery_empty_voltage = 3.4
battery_full_voltage = 4.0

# --------------------------------
# Sensors
# --------------------------------

# execution command example:
# mads-filter tip_loadcell -o side=left -b
[tip_loadcell]
sub_topic = ["coordinator"]
pub_topic = "tip_loadcell"
datapin = 6
clockpin = 26
period = 10
side = "unknown" # used to select scaling factor
health_status_period = 500 # ms

[tip_loadcell.scaling]
left = 1.0 # debug value
right = 1.2 # debug value


# execution command example:
# mads-filter handle_loadcell -o side=left --dont-block
[handle_loadcell]
sub_topic = ["coordinator"] # power_status is used to adapt the ADC's reference voltage in realtime reading from the "supply_voltage" field
pub_topic = "handle_loadcell"
period = 20
ref_voltage = 4.12
adc1_rate = 9 # ADS1263 rate index, default 9 = 1200 SPS, but raspberry can reach maximum 100Hz
side = "unknown" # used to select scaling factors
health_status_period = 500 # ms
# Adjust the input number with the connected loadcell's label
# Default is:
#  IN0, IN1, IN2, IN3, IN4, IN5, IN6, IN7 
# "up_front", "up_back", "right_front", "right_back", "left_front", "left_back","down_front", "down_back"
input_map = [[0, "up_front"], [1, "up_back"], [2, "right_front"], [3, "right_back"], [4, "left_front"], [5, "left_back"], [6, "down_front"], [7, "down_back"]]

[handle_loadcell.range_map]
left = [[0, 500.0], [1, 500.0], [2, 50.0], [3, 50.0], [4, 50.0], [5, 50.0], [6, 50.0], [7, 50.0]] # IN0, IN1, IN2, IN3, IN4, IN5, IN6, IN7
right = [[0, 500.0], [1, 500.0], [2, 50.0], [3, 50.0], [4, 50.0], [5, 50.0], [6, 50.0], [7, 50.0]] # IN0, IN1, IN2, IN3, IN4, IN5, IN6, IN7

# execution command example:
# source venv/bin/activate
# python ppg.py -o side=left
[ppg]
sub_topic = ["coordinator"]
pub_topic = "ppg"
health_status_period = 500 # ms
period = 10 # ms, 100 Hz
side = "unknown"

# execution command example:
# source venv/bin/activate
# python ppg.py 
[pupil_neon]
sub_topic = ["coordinator"]
pub_topic = "pupil_neon"
health_status_period = 500 # ms

# --------------------------------
# HDF5 Loggers
# --------------------------------

# execution command examples:
# mads-filter hdf5_writer -b 
# Note: if you add more than one keypath for the "coordinator" topic, it is not guaranteed that the fields have the same size (it depends if the "A" field is always present when the "B" field is present, etc)
[hdf5_writer]
sub_topic = ["coordinator", "tip_loadcell", "handle_loadcell", "ppg", "pupil_neon"]
pub_topic = "hdf5_writer"
folder_path = "/home/crutch/instrumented_crutches_mads/web_server/data" # path to save the hdf5 files, make sure the agent has write access to this folder
#folder_path = "C:\mirrorworld\instrumented_crutches_mads\web_server\data" # Windows path example
keypaths = {"coordinator" = ["label"], "tip_loadcell" = ["side", "force"], "handle_loadcell" = ["side", "force.up_front", "force.up_back", "force.down_front", "force.down_back", "force.left_front", "force.left_back", "force.right_front", "force.right_back"], "ppg" = ["side", "ir", "red"], "pupil_neon" = ["time_offset_ms_mean", "time_offset_ms_std", "time_offset_ms_median", "roundtrip_duration_ms_mean", "roundtrip_duration_ms_std", "roundtrip_duration_ms_median"]}
health_status_period = 500 # ms


