/*
  _____ _ _ _                    _             _       
 |  ___(_) | |_ ___ _ __   _ __ | |_   _  __ _(_)_ __  
 | |_  | | | __/ _ \ '__| | '_ \| | | | |/ _` | | '_ \ 
 |  _| | | | ||  __/ |    | |_) | | |_| | (_| | | | | |
 |_|   |_|_|\__\___|_|    | .__/|_|\__,_|\__, |_|_| |_|
                          |_|            |___/         
# A Template for LoadcellPlugin, a Filter Plugin
# Generated by the command: C:\Program Files\MADS\usr\local\bin\mads-plugin.exe -t filter -d C:\mirrorworld\instrumented_crutches\loadcell loadcell
# Hostname: unknown
# Current working directory: C:\mirrorworld\instrumented_crutches
# Creation date: 2026-01-11T18:28:16.919+0100
# NOTICE: MADS Version 1.4.0
*/

// To run this plugin remember to use the command with the --dont-block option enabled to avoid blocking while waiting for new data in sub_topic
// mads-filter loadcell.plugin --dont-block 

// Mandatory included headers
#include <filter.hpp>
#include <nlohmann/json.hpp>
#include <pugg/Kernel.h>

// other includes as needed here

// Define the name of the plugin
#ifndef PLUGIN_NAME
#define PLUGIN_NAME "loadcell"
#endif

// Load the namespaces
using namespace std;
using json = nlohmann::json;


// Plugin class. This shall be the only part that needs to be modified,
// implementing the actual functionality
class LoadcellPlugin : public Filter<json, json> {

public:

  // Typically, no need to change this
  string kind() override { return PLUGIN_NAME; }

  // Implement the actual functionality here
  return_type load_data(json const &input, string topic = "") override {
    
    // if topic is "command", process commands here
    if (topic == "command" && input.contains("command")) {
      string action = input["command"];
      if (action == "start" && _acquiring == false) {
        _acquiring = true;
        std::cout << "Loadcell: Starting acquisition" << std::endl;
        // other actions as needed
      } else if (action == "stop" && _acquiring == true) {
        _acquiring = false;
        std::cout << "Loadcell: Stopping acquisition" << std::endl;
        // other actions as needed
      } else if (action == "set_offset" && _acquiring == false) {
        _setting_offset = true;
        std::cout << "Loadcell: Setting offset" << std::endl;
      } else {
        return return_type::retry;
      }
    }

    return return_type::success;
  }

  // We calculate the average of the last N values for each key and store it
  // into the output json object
  return_type process(json &out) override {
    out.clear();

    // load the data as necessary and set the fields of the json out variable
    if (_acquiring) {
      auto now = std::chrono::system_clock::now();
      out["ts_" + _params["side"].get<string>()] = std::chrono::duration_cast<std::chrono::milliseconds>(now.time_since_epoch()).count();

      float test = 0.0;
      if (_params["side"] == "right") // Simulate different readings for left and right
        test = 200.0;
      
      out[_params["side"]] = test + _debug_offset + (rand() % 100 - 50) - _offset; // Dummy data 

    } else if (_setting_offset && _acquiring == false) {
      _offset = _debug_offset;
      _setting_offset = false;
      std::cout << "Loadcell: Offset set to " << _offset << std::endl;

    } else {
      return return_type::retry;
    }

    // This sets the agent_id field in the output json object, only when it is
    // not empty
    if (!_agent_id.empty()) out["agent_id"] = _agent_id;
    return return_type::success;
  }
  
  void set_params(void const *params) override {
    // Call the parent class method to set the common parameters 
    // (e.g. agent_id, etc.)
    Filter::set_params(params);

    // provide sensible defaults for the parameters by setting e.g.
    _params["side"] = "unknown";

    _debug_offset = (rand() % 100 - 50); // Emulate some offset value

    // then merge the defaults with the actually provided parameters
    // params needs to be cast to json
    _params.merge_patch(*(json *)params);

    if (_params.contains("side")) {
      std::cout << "Loadcell: Side set to " << _params["side"] << std::endl;
    } else {
      std::cout << "Loadcell: Side parameter not set, using default 'unknown'" << std::endl;
      throw std::runtime_error("Loadcell: side parameter is required");
    }
      
  }

  // Implement this method if you want to provide additional information
  map<string, string> info() override { 
    // return a map of strings with additional information about the plugin
    // it is used to print the information about the plugin when it is loaded
    // by the agent
    
    return {};
    
  };

private:
  // Define the fields that are used to store internal resources

  // Control flags
  bool _acquiring = false;
  bool _setting_offset = false;

  // Internal variables
  float _debug_offset = 0.0;
  float _offset = 0.0;
  
};


/*
  ____  _             _             _      _
 |  _ \| |_   _  __ _(_)_ __     __| |_ __(_)_   _____ _ __
 | |_) | | | | |/ _` | | '_ \   / _` | '__| \ \ / / _ \ '__|
 |  __/| | |_| | (_| | | | | | | (_| | |  | |\ V /  __/ |
 |_|   |_|\__,_|\__, |_|_| |_|  \__,_|_|  |_| \_/ \___|_|
                |___/
Enable the class as plugin
*/
INSTALL_FILTER_DRIVER(LoadcellPlugin, json, json);


/*
                  _       
  _ __ ___   __ _(_)_ __  
 | '_ ` _ \ / _` | | '_ \ 
 | | | | | | (_| | | | | |
 |_| |_| |_|\__,_|_|_| |_|
                          
*/

int main(int argc, char const *argv[])
{
  LoadcellPlugin plugin;
  json params;
  json input, output;

  // Set example values to params
  params["test"] = "value";

  // Set the parameters
  plugin.set_params(&params);

  // Set input data
  input["data"] = {
    {"AX", 1},
    {"AY", 2},
    {"AZ", 3}
  };

  // Set input data
  plugin.load_data(input);
  cout << "Input: " << input.dump(2) << endl;

  // Process data
  plugin.process(output);
  cout << "Output: " << output.dump(2) << endl;


  return 0;
}

