/*
  _____ _ _ _                    _             _       
 |  ___(_) | |_ ___ _ __   _ __ | |_   _  __ _(_)_ __  
 | |_  | | | __/ _ \ '__| | '_ \| | | | |/ _` | | '_ \ 
 |  _| | | | ||  __/ |    | |_) | | |_| | (_| | | | | |
 |_|   |_|_|\__\___|_|    | .__/|_|\__,_|\__, |_|_| |_|
                          |_|            |___/         
# A Template for TipLoadcellPlugin, a Filter Plugin
# Generated by the command: C:\Program Files\MADS\usr\local\bin\mads-plugin.exe -t filter -d C:\mirrorworld\instrumented_crutches\tip_loadcell tip_loadcell
# Hostname: unknown
# Current working directory: C:\mirrorworld\instrumented_crutches
# Creation date: 2026-01-11T18:28:16.919+0100
# NOTICE: MADS Version 1.4.0
*/

// To run this plugin remember to use the command with the --dont-block option enabled to avoid blocking while waiting for new data in sub_topic
// mads-filter tip_loadcell.plugin -o side=left --dont-block 

// Mandatory included headers
#include <filter.hpp>
#include <nlohmann/json.hpp>
#include <pugg/Kernel.h>

// other includes as needed here
#include <memory>          // For std::unique_ptr
#include <chrono>          // For time handling

// Include HX711 for Raspberry Pi
#include <hx711/common.h>  // Library for HX711
using namespace HX711;

// Define the name of the plugin
#ifndef PLUGIN_NAME
#define PLUGIN_NAME "tip_loadcell"
#endif

// Load the namespaces
using namespace std;
using json = nlohmann::json;

// Plugin class. This shall be the only part that needs to be modified,
// implementing the actual functionality
class TipLoadcellPlugin : public Filter<json, json> {

public:

  // Constructor
  TipLoadcellPlugin() : _hx(nullptr) {}

  // Typically, no need to change this
  string kind() override { return PLUGIN_NAME; }

  // Implement the actual functionality here
  return_type load_data(json const &input, string topic = "") override {
    
    // if topic is "command", process commands here
    if (topic == "command") {
      if (!input.contains("command")) {
        return return_type::retry;
      }

      string action = input["command"];
      if (action == "start") {
        if (_acquiring) {
          _error = "Tip Loadcell: start requested while already acquiring";
          std::cout << std::endl << "\033[31m" << "Error: " << _error << "\033[0m" << std::endl;
          return return_type::warning;
        }
        _acquiring = true;
        std::cout << std::endl << "Tip Loadcell: Starting acquisition" << std::endl;
      } else if (action == "stop") {
        if (_acquiring == false) {
          _error = "Tip Loadcell: stop requested while not acquiring";
        std::cout << std::endl << "\033[31m" << "Error: " << _error << "\033[0m" << std::endl;
          return return_type::warning;
        }
        _acquiring = false;
        std::cout << std::endl << "Tip Loadcell: Stopping acquisition" << std::endl;
      } else if (action == "set_offset") {
        if (_acquiring) {
          _error = "Tip Loadcell: set_offset not allowed while acquiring, request ignored";
        std::cout << std::endl << "\033[31m" << "Error: " << _error << "\033[0m" << std::endl;
          return return_type::error;
        }
        _setting_offset = true;
        std::cout << std::endl << "Tip Loadcell: Setting offset" << std::endl;
      } else {
        _error = "Tip Loadcell: unknown command '" + action + "'";
        std::cout << std::endl << "\033[31m" << "Error: " << _error << "\033[0m" << std::endl;
        return return_type::error;
      }
    }

    return return_type::success;
  }

  // We calculate the average of the last N values for each key and store it
  // into the output json object
  return_type process(json &out) override {
    out.clear();

    // Not valid states or transitions are handled in load_data, here we just process data
    // Here we should have only valid states and errors related to reading the sensor

    // load the data as necessary and set the fields of the json out variable
    if (_acquiring) {

      try {
        if (_hx && _enabled) {
          auto time = std::chrono::duration_cast<std::chrono::milliseconds>(std::chrono::system_clock::now().time_since_epoch()).count();
          double loadCellValue = _hx->weight(1).getValue(Mass::Unit::N);

          out["force"][_side] = loadCellValue - _offset;
          out["time"][_side] = time; 

        }
      } catch (const std::exception &e) {
        _error = "Tip Loadcell: Error reading from HX711: " + string(e.what());
        return return_type::warning;
      }
      
    } else if (_setting_offset && _acquiring == false) {
      try {
        // Real hardware offset on Raspberry Pi
        _offset = _hx->weight(20).getValue(Mass::Unit::N);
        _setting_offset = false;

        // test read after setting offset
        auto offset_test = _hx->weight(20).getValue(Mass::Unit::N) - _offset;
        
        // Store the offset and the test read in the output json for user feedback
        // We only fill the field for the current side
        out["offset"][_side] = _offset;
        out["offset_test"][_side] = offset_test;

      } catch (const std::exception &e) {
        _error = "Tip Loadcell: Error reading from HX711 for offset: " + string(e.what());
        return return_type::warning;
      }
      
    } else {
      return return_type::retry;
    }

    // This sets the agent_id field in the output json object, only when it is
    // not empty
    if (!_agent_id.empty()) out["agent_id"] = _agent_id;
    return return_type::success;
  }
  
  void set_params(const json &params) override {
    // Call the parent class method to set the common parameters 
    // (e.g. agent_id, etc.)
    Filter::set_params(params);

    // provide sensible defaults for the parameters by setting e.g.
    _params["side"] = "unknown";

    // then merge the defaults with the actually provided parameters
    // params needs to be cast to json
    _params.merge_patch(params);

    if (_params.contains("side") && (_params["side"] == "left" || _params["side"] == "right")) {
      _side = _params["side"].get<string>();
      std::cout << "Tip Loadcell: Side set to " << _side << std::endl;
    } else {
      _error = "Tip Loadcell: Side parameter not set or invalid (only 'left' or 'right' allowed).";
      std::cout << _error << std::endl;
      throw std::runtime_error(_error);
    }

    // Read configuration parameters for the single HX711 sensor
    _enabled = _params.value("enabled", true);  // Default to true if not specified
    int dataPin = _params.value("datapin", 6); // default data pin 6 based on typical Raspberry Pi wiring for HX711
    int clockPin = _params.value("clockpin", 26); // default clock pin 26 based on typical Raspberry Pi wiring for HX711

    if (_params.contains("scaling") && _params["scaling"].contains(_side)) {
      double scaling = _params["scaling"][_side].get<double>();
    } else {
      _error = "Tip Loadcell: Scaling factor for side '" + _side + "' not found in scaling parameter.";
      std::cout << _error << std::endl;
      throw std::runtime_error(_error);
    }

    // Initialize the HX711 sensor
    if (_enabled && dataPin != -1 && clockPin != -1) {
      _hx = std::make_unique<AdvancedHX711>(dataPin, clockPin, scaling, 0.0, Rate::HZ_80);
      std::cout << "Tip Loadcell: HX711 initialized with dataPin=" << dataPin 
                << ", clockPin=" << clockPin << ", scaling=" << scaling << std::endl;
    }

    _setting_offset = true; // Set offset at the beginning
  }

  // Implement this method if you want to provide additional information
  map<string, string> info() override { 
    // return a map of strings with additional information about the plugin
    // it is used to print the information about the plugin when it is loaded
    // by the agent
    
    return {};
    
  };

private:
  // Define the fields that are used to store internal resources
  unique_ptr<AdvancedHX711> _hx;  // Single HX711 sensor

  // Control flags
  bool _enabled = false;
  bool _acquiring = false;
  bool _setting_offset = false;

  // Internal variables
  string _side = "unknown";
  float _offset = 0.0;
  
};


/*
  ____  _             _             _      _
 |  _ \| |_   _  __ _(_)_ __     __| |_ __(_)_   _____ _ __
 | |_) | | | | |/ _` | | '_ \   / _` | '__| \ \ / / _ \ '__|
 |  __/| | |_| | (_| | | | | | | (_| | |  | |\ V /  __/ |
 |_|   |_|\__,_|\__, |_|_| |_|  \__,_|_|  |_| \_/ \___|_|
                |___/
Enable the class as plugin
*/
INSTALL_FILTER_DRIVER(TipLoadcellPlugin, json, json);


/*
                  _       
  _ __ ___   __ _(_)_ __  
 | '_ ` _ \ / _` | | '_ \ 
 | | | | | | (_| | | | | |
 |_| |_| |_|\__,_|_|_| |_|
                          
*/

int main(int argc, char const *argv[])
{
  TipLoadcellPlugin plugin;
  json params;
  json input, output;

  // Set example values to params
  params["test"] = "value";

  // Set the parameters
  plugin.set_params(params);

  // Set input data
  input["data"] = {
    {"AX", 1},
    {"AY", 2},
    {"AZ", 3}
  };

  // Set input data
  plugin.load_data(input);
  cout << "Input: " << input.dump(2) << endl;

  // Process data
  plugin.process(output);
  cout << "Output: " << output.dump(2) << endl;


  return 0;
}

